name: gelato
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  go_router: ^15.1.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.8.3
  image_picker: ^1.0.7
  firebase_storage: ^11.5.4
  firebase_app_check: ^0.2.1+6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo2.png
