// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gG6RzqjRkFUYQFMKRb4-zrjZxPRNX_Y',
    appId: '1:146376464039:web:aff03097f87b4113cb2d82',
    messagingSenderId: '146376464039',
    projectId: 'gelato-fd448',
    authDomain: 'gelato-fd448.firebaseapp.com',
    storageBucket: 'gelato-fd448.firebasestorage.app',
    measurementId: 'G-SC3KJ2T0P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkAjBGHuqzx8wVI7IIG05qtafxwbOxfuQ',
    appId: '1:146376464039:android:f375f6ebcff5046dcb2d82',
    messagingSenderId: '146376464039',
    projectId: 'gelato-fd448',
    storageBucket: 'gelato-fd448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLa0ehEHYaMrvtMMvkEPERAoVt2grO3Eg',
    appId: '1:146376464039:ios:6c6ff6b157e89cc3cb2d82',
    messagingSenderId: '146376464039',
    projectId: 'gelato-fd448',
    storageBucket: 'gelato-fd448.firebasestorage.app',
    iosBundleId: 'com.aulaGelato.gelato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLa0ehEHYaMrvtMMvkEPERAoVt2grO3Eg',
    appId: '1:146376464039:ios:6c6ff6b157e89cc3cb2d82',
    messagingSenderId: '146376464039',
    projectId: 'gelato-fd448',
    storageBucket: 'gelato-fd448.firebasestorage.app',
    iosBundleId: 'com.aulaGelato.gelato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5gG6RzqjRkFUYQFMKRb4-zrjZxPRNX_Y',
    appId: '1:146376464039:web:99a12bec9a6d4b88cb2d82',
    messagingSenderId: '146376464039',
    projectId: 'gelato-fd448',
    authDomain: 'gelato-fd448.firebaseapp.com',
    storageBucket: 'gelato-fd448.firebasestorage.app',
    measurementId: 'G-E16K8S7Y1Q',
  );
}
